### ISSUE TITLE
GUI bug

### ISSUE THREAD

**Issue by ohrules** [hussamh10/fuzzy-finder#26]
If the **first** result of a query is already open, the GUI is messed up. See screenshot.
![image](https://user-images.githubusercontent.com/13495205/36051542-4a761b98-0e0c-11e8-8917-b2d7c7ed94bc.png)

@Haroon96

**Comment by Haroon96** [comment]
Bug caused by incorrect height calculation when number of results was less than 5. Result folder being currently open was coincidental.
