### ISSUE TITLE
Add autohotkey

### ISSUE THREAD

**Issue by hussamh10** [hussamh10/fuzzy-finder#34]
![ahks](https://user-images.githubusercontent.com/11413675/36635156-e5f7715e-19d1-11e8-8f09-2eded0023174.jpeg)

this is actually a .rar file.

in it are the exe and ahk for mapping of win+space to F9

**Comment by hussamh10** [comment]
use wget to dnld :P

**Comment by Haroon96** [comment]
Changed launch modifier to Ctrl+Space in-app.
