### ISSUE TITLE
Fix GUI

### ISSUE THREAD

**Issue by hussamh10** [hussamh10/fuzzy-finder#4]
- Add space support to enable parent dir search
- Fix special characters

**Comment by hussamh10** [comment]
![image](https://user-images.githubusercontent.com/11413675/35696197-a59a83ca-07a8-11e8-9b8c-f6e7a34c8120.png)
CENTER KARAIN ISSAY !! (On 1080)
also maybe move to the top a bit.

**Comment by hussamh10** [comment]
Also move the gui to the top

**Comment by Haroon96** [comment]
GUI moved to top. Allowed space insertion. Removed early size change and issues due to special characters.
