### ISSUE TITLE
Make Linux compatible

### ISSUE THREAD

**Issue by hussamh10** [hussamh10/fuzzy-finder#5]
- [ ] Make front end compatible
- [x] Make indexing compatible

**Comment by hussamh10** [comment]
Indexing already cross plat. :3

**Comment by Haroon96** [comment]
Add compat for space scoring

**Comment by hussamh10** [comment]
Can this even be made cross plat ?
And should we even bother ?

**Comment by hussamh10** [comment]
Not supporting Linux
