### ISSUE TITLE
Change the GUI List format

### ISSUE THREAD

**Issue by hussamh10** [hussamh10/fuzzy-finder#6]
Change the 'auto-complete' list to also show the path of the folders so the user could differentiate between  duplicates.

**Comment by Haroon96** [comment]
![image](https://user-images.githubusercontent.com/25146962/35815597-ad1eaff8-0aba-11e8-9504-f5f77f87f14a.png)
gui list format updated to include folder path as well. @hussamh10 include drive letter as well.

**Comment by hussamh10** [comment]
Done
