### ISSUE TITLE
Make indexing periodic

### ISSUE THREAD

**Issue by hussamh10** [hussamh10/fuzzy-finder#8]
- Enable auto indexing
- Enable indexing when changes in dir (possible?)

**Comment by hussamh10** [comment]
Call indexer from front end. 
`python libs/index.py`
Call this every 12 hours.

**Comment by Haroon96** [comment]
libs/index.py is called every one hour.

**Comment by Haroon96** [comment]
Program should index to a temp file and then swap the original index and the temp to prevent dirty reads.

**Comment by hussamh10** [comment]
Done, added indexed_temp that is renamed indexed after indexing.
